### ISSUE TITLE
Ensure the attribution is sufficient

### ISSUE THREAD

**Issue by nfrisby** [nfrisby/haskell-base32768#1]
How best to attribute this to @qntm? Should "qntm" be listed in the LICENSE / copyright field?

**Comment by nfrisby** [comment]
@qntm I'm happy to do whatever you'd prefer here. Thanks.

**Comment by qntm** [comment]
I really don't mind all that much, some kind of acknowledgement along the lines of "The Base32768 encoding originally created by qntm" somewhere would be fine.
